### ISSUE TITLE
v1.0.0 Roadmap

### ISSUE THREAD

**Issue by timche** [acdlite/redux-actions#122]
With v1.0.0 we are releasing our first version that comes with breaking changes:

## Breaking Changes:
- [x] #115: Only omit payload if undefined
- [ ] #127: Make defaultState required when creating reducers
- [x] #145: Fail early for non-FSA actions

**Comment by timche** [comment]
I would also like to introduce [Flowtype](https://flowtype.org/) with this version as it is getting popular and already being used in many React application as well as in [create-react-app](https://github.com/facebookincubator/create-react-app).

cc @yangmillstheory

**Comment by yangmillstheory** [comment]
Sounds good.

I remember you had a great idea to clean up the documentation too. Just wanted to make sure that's not forgotten (not sure which epic it goes in).

**Comment by timche** [comment]
Oh, yeah, documentation cleanup/improvement would also be nice. I will add it.

**Comment by timche** [comment]
Because #115 seems to be more relevant than expected, we can release that as only change in v1.0.0 and everything else after to speed up the release.

cc @yangmillstheory

**Comment by yangmillstheory** [comment]
That sounds good. Are you going to take #115?

**Comment by timche** [comment]
Yes @yangmillstheory

**Comment by yangmillstheory** [comment]
@timche can I take care of #47 in v1.0.0?

**Comment by timche** [comment]
That would be huge breaking change. Could be sth for v2.

**Comment by yangmillstheory** [comment]
What about #18? 

I'm not sure if this would also be breaking actually, since I think Redux throws errors on missing default state.

#18 just ensures the errors are thrown earlier.

**Comment by timche** [comment]
Yes, this is actually breaking, since we are making this required, even it was throwing an error before.

**Comment by yangmillstheory** [comment]
OK. Please see #127 😄 .

**Comment by yangmillstheory** [comment]
Can we add type-checking of `payloadCreator` and `metaCreator` to this?

See the first example in https://github.com/acdlite/redux-actions/pull/128#issuecomment-244896176.

**Comment by yangmillstheory** [comment]
I've ported this roadmap issue over to https://github.com/acdlite/redux-actions/projects/1.
